# Generated by Django 5.2.14 on 2026-06-04 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memberShip", "0001_initial"),
        ("userAcount", "0003_remove_dataset_file_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="membership_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="memberShip.membershipplan",
            ),
        ),
    ]
