# Generated by Django 5.2.14 on 2026-06-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userAcount", "0004_alter_user_membership_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
